DROP TABLE IF EXISTS diary_entry;
DROP TABLE IF EXISTS user_media;
DROP TABLE IF EXISTS musics;
DROP TABLE IF EXISTS shows;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS music_type;
DROP TYPE IF EXISTS show_type;
DROP TYPE IF EXISTS book_type;
DROP TYPE IF EXISTS film_type;
DROP TYPE IF EXISTS media_type;